# Generated by Django 2.2.5 on 2019-09-15 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='secret'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
