# Generated by Django 2.2.5 on 2019-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20190915_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='upvotes',
            field=models.IntegerField(default=1, verbose_name='upvotes'),
        ),
    ]
